apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "dev"
secretGenerator:
- name: mysql-pass
  literals:
  - password=xR3W4Yc73t]H
secretGenerator:
- name: freejqm8-myshala
  literals:
  - password=HfOQURq8}Imd
resources:
  - mysql-deploy.yaml
  - wp-deploy.yaml
  - wp-gw-vs.yaml
  - adminer-gw-vs.yaml
