apiVersion: v1
kind: Secret
namespace: "dev"
metadata:
  name: mysql-root-pass
type: Opaque
data:
  PASSWORD: xR3W4Yc73t]H
---
apiVersion: v1
kind: Secret
namespace: "dev"
metadata:
  name: freejqm8-myshala
type: Opaque
data:
  PASSWORD: HfOQURq8}Imd
